### PR TITLE
remove LP validation.

### PR DESCRIPTION
**Pull request by beliaev-maksim**
All future validations should be done using GitHub username or commit email via the new API endpoint instead of membership

* remove launchpad verification
* remove `actions.exec` direct dependency 
* re-run `npm install`

### CODE REVIEW

**Review by simondeziel — COMMENTED** [review]
LGTM but I don't know NPM much so I'm wondering if `node_modules/@actions/exec` can now go as well?

**Comment by beliaev-maksim** [comment]
@simondeziel right, good spot, let me re-compile the package

**Review by seb128 — APPROVED** [review]
Seems fine to me but could you try to send an announce for users of the action to warn them about the behaviour change?

Could you also try to get the description of https://ubuntu.com/legal/contributors updated to mention that it isn't used anymore?

**Comment by beliaev-maksim** [comment]
> Could you also try to get the description of https://ubuntu.com/legal/contributors updated to mention that it isn't used anymore?

@seb128 the entire frontend and backend will be changed. Community team will draft a separate post about it, thus, do not think it is a good idea to talk about mechanics of the implementation on the CLA front page

**Pull request merged**
