### PR TITLE
Remove Mozilla and Ocado from CLA

### PR DESCRIPTION
**Pull request by beliaev-maksim**
Based on internal discussion, those companies do not have signed CLA, thus, each individual would need to sign by themselves

https://docs.google.com/document/d/10jnAq1LODM141eV6s4n0UP6XYhDM4PCZF_wKX2hys-A/edit?disco=AAABLNrgMT8

### CODE REVIEW

**Comment by beliaev-maksim** [comment]
reject as we do massive refactoring

**Review by seb128 — CHANGES_REQUESTED** [review]
I'm trying to get some background on the Mozilla special case there. They own the Firefox snap and the Vcs is currently hosted under the Canonical organization so I think we need to sort out that situation before doing the change.

**Review by seb128 — CHANGES_REQUESTED** [review]
Mozilla has signed the CLA now, can we amend the change accordingly?

**Review by seb128 — APPROVED** [review]
Maksim clarified that those expections will be added to the service and such don't need to be included in the action source, thanks

**Pull request merged**
