### PR TITLE
Update release to 1.2.0

### PR DESCRIPTION
**Pull request by lengau**
* Updates release version in package.json
* Fixes npm audit issues in package-lock.json and node_modules (#29)
* Includes feature for configurable bots (see #27)

### CODE REVIEW

**Comment by lengau** [comment]
@seb128 sorry to bother you again, but I've made a release for the change I made earlier and updating dependencies.

Since PRs can't include tags, if you're ok with these changes I'd appreciate it if you could add a `v1.2.0` tag and move the `v1` tag to the commit of this completed PR

**Review by seb128 — APPROVED** [review]
I'm going to trust you on this one, it's not really a reviewable patchset

**Comment by seb128** [comment]
and v1 has been moved to point to 1.2.0

**Comment by lengau** [comment]
Thank you! I really appreciate it :-)

Fortunately if I do anything evil you can get @sergiusens on me for it.

**Pull request merged**
