### PR TITLE
Remove `accept-existing-contributors` option

### PR DESCRIPTION
**Pull request by beliaev-maksim**
* Remove the option for accepting existing contributors, as contributors can revoke their CLA agreement. The CLA must be checked with every commit.

### CODE REVIEW

**Review by seb128 — CHANGES_REQUESTED** [review]
Thank you for the changes. 

While I can't argue against what the legal team is asking us for I disagree with merging those changes now. Those options are being used today and some projects rely on them, we should make a announce about incoming changes ahead of landing the PR. We should also bump the action version as part of the change which should allow for an easier transition. It seems most repo use "v1" of the action which lowers the impact if we land the change in a newer version but still announcing will let maintainers know that there is a new version and that those policies are what will be enforced going forward

And one small extra asks, could you rework the commits? The 'update README' changes could at least be squashed, ideally description edits would go in the same commit as the corresponding code changes since that's one logical unit. Basically that should be  commits
- README formatting tweaks
- removing exiting contributor option, including the corresponding documentation change
- removing license approval option, including the corresponding documentation change

**Comment by beliaev-maksim** [comment]
@seb128 I agree that this PR is destructive since introduces backwards incompatible changes. However, pinning to `main` is the same as pinning to the `edge` channel. You subscribe to the development branch. 
Users should either pin `v1` or `v1.x`

as for commits, of course, I can rework those. However, all of them will be squashed at PR merge anyway, that allows to keep linear history in the repo

**Comment by seb128** [comment]
> as for commits, of course, I can rework those. However, all of them will be squashed at PR merge anyway, that allows to keep linear history in the repo

The merge vs squash is sort of maintainer preference. I was not going to squash in those case since the individual commits are logical units which makes sense and splitting them makes browsing history easier

**Review by seb128 — APPROVED** [review]
Thanks!

**Pull request merged**
